runtime: python311
service: default
entrypoint: gunicorn -b :$PORT app:app
service_account: githubsa@project-5b58ef08-5d18-4111-846.iam.gserviceaccount.com
manual_scaling:
  instances: 3
  #automatic_scaling:
  #min_instances: 1
  #max_instances: 5
  #target_cpu_utilization: 0.6
  #target_throughput_utilization: 0.6
