replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/project-5b58ef08-5d18-4111-846/my-repo/pythonapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

containerPort: 5000

environment:
  ENVIRONMENT: production

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 512Mi