apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-backend
  template:
    metadata:
      labels:
        app: python-backend
    spec:
      containers:
      - name: python-backend
        image: us-central1-docker.pkg.dev/project-5b58ef08-5d18-4111-846/test/backend:v0.1
        ports:
        - containerPort: 5000
