name: GKE CI/CD

on:
 push:
   branches:
     - main
     - test
 workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        
      - name: run a command
        run: echo "Running this CI workflow"
        
