name: GKE CI/CD

on:
 push:
   branches:
     - main
     - test
 workflow_dispatch:

permissions:
  contents: 'read'
  id-token: 'write'
  
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: us-central1
  GAR_REPOSITORY: my-repo
  IMAGE_NAME: pythonapp
  GKE_CLUSTER: gke-dr-primary
  GKE_LOCATION: us-central1
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Authenticate to Google cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Verify GCP authentication
        run: |
         gcloud auth list
         gcloud config list
         
      - name: Configure docker authentication
        run: |
         gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker Image
        run: |
         docker build -t us-central1-docker.pkg.dev/project-5b58ef08-5d18-4111-846/my-repo/$IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker Image
        run: |
         docker push us-central1-docker.pkg.dev/project-5b58ef08-5d18-4111-846/my-repo/$IMAGE_NAME:${{ github.sha }}
  
  deploy-job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        
      - name: Authenticate to Google cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v3
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_LOCATION }}
          project_id: ${{ env.PROJECT_ID }}
          
      - name: Verify GKE access
        run: |
          kubectl get nodes
          kubectl apply -f 27-july/k8s_Files/
  
