name: Deploy python app to cloud Run

on:
 push:
  branches:
    - main
 workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: us-central1
  REPOSITORY: test
  SERVICE: pythoncloud-service

jobs:

  deploy:

   name: Build and Deploy
   runs-on: ubuntu-latest

   permissions:
    contents: read
    id-token: write

   steps:
   - name: Checkout
     uses: actions/checkout@v4

   - name: Authenticate to Google cloud
     uses: google-github-actions/auth@v2
     with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

   - name: Setup gcloud
     uses: google-github-actions/setup-gcloud@v2
   
   - name: Configure docker authentication
     run: |
      gcloud auth configure-docker us-central1-docker.pkg.dev
  
   - name: Build Docker Image
     run: |
         docker build -t us-central1-docker.pkg.dev/project-5b58ef08-5d18-4111-846/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }} .

   - name: Push Docker Image
     run: |
      docker push us-central1-docker.pkg.dev/project-5b58ef08-5d18-4111-846/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
   - name: Deploy to Cloud Run
     run: |
      gcloud run deploy "$SERVICE" \
      --image: us-central1-docker.pkg.dev/project-5b58ef08-5d18-4111-846/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }} \
      --region "$GAR_LOCATION" \
      --platform managed \
      --port 5000 \
      --allow-unauthenticated \
      --set-env-vars ENVIRONMENT=production 